name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - dev
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - run: npm run pack
    - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        title: 'My Issues Report'
        outputPath: 'IssuesReport.md'
        configPath: 'issues-report.json'