name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - dev
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - run: npm run pack
    - run: npm test
    - uses: actions/upload-artifact@v2
      with:
        # This file gets produced by main.test.ts
        name: test-markdown
        path: test/result.md

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        title: 'My Issues Report'
        outputPath: 'IssuesReport.md'
        configPath: 'test/issues-report.json'
        token: ${{ secrets.GITHUB_TOKEN }}
